services:
  party-manager-api:
    container_name: party-manager-api
    build:
      context: .
      dockerfile: Dockerfile
    image: party-manager-api:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JAVA_OPTS: "-Xms256m -Xmx512m"
